project_id = "srwnjnrhxzcpftmbbyib"

[functions.sync-orquest-services]
verify_jwt = true

[functions.invoice-ocr]
verify_jwt = true

[functions.search-company-data]
verify_jwt = true

[functions.journal-import]
verify_jwt = true

[functions.pl-rubric-breakdown]
verify_jwt = true

[functions.ap-learning]
verify_jwt = true

[functions.split-pdf]
verify_jwt = true

[functions.merge-pdf]
verify_jwt = true

[functions.api-example]
verify_jwt = false
